time python preprocess.py -i /media/storage/Experiments/DataSets/ISI_100KReq/ISI1 -o /media/storage/Experiments/DataSets/filtered/ISI_100KReq/ISI1
time python preprocess.py -i /media/storage/Experiments/DataSets/ISI_100KReq/ISI2 -o /media/storage/Experiments/DataSets/filtered/ISI_100KReq/ISI2
time python preprocess.py -i /media/storage/Experiments/DataSets/ISI_100KReq/ISI3 -o /media/storage/Experiments/DataSets/filtered/ISI_100KReq/ISI3
time python preprocess.py -i /media/storage/Experiments/DataSets/ISI_100KReq/ISI4 -o /media/storage/Experiments/DataSets/filtered/ISI_100KReq/ISI4
time python preprocess.py -i /media/storage/Experiments/DataSets/ISI_100KReq/ISI5 -o /media/storage/Experiments/DataSets/filtered/ISI_100KReq/ISI5
time python preprocess.py -i /media/storage/Experiments/DataSets/ISI_100KReq/ISI6 -o /media/storage/Experiments/DataSets/filtered/ISI_100KReq/ISI6
time python preprocess.py -i /media/storage/Experiments/DataSets/ISI_100KReq/ISI7 -o /media/storage/Experiments/DataSets/filtered/ISI_100KReq/ISI7
time python preprocess.py -i /media/storage/Experiments/DataSets/ISI_1MReq/ISI1 -o /media/storage/Experiments/DataSets/filtered/ISI_1MReq/ISI1
time python preprocess.py -i /media/storage/Experiments/DataSets/ISI_1MReq/ISI2 -o /media/storage/Experiments/DataSets/filtered/ISI_1MReq/ISI2
time python preprocess.py -i /media/storage/Experiments/DataSets/ISI_1MReq/ISI3 -o /media/storage/Experiments/DataSets/filtered/ISI_1MReq/ISI3
time python preprocess.py -i /media/storage/Experiments/DataSets/ISI_1MReq/ISI4 -o /media/storage/Experiments/DataSets/filtered/ISI_1MReq/ISI4
time python preprocess.py -i /media/storage/Experiments/DataSets/ISI_1MReq/ISI5 -o /media/storage/Experiments/DataSets/filtered/ISI_1MReq/ISI5
time python preprocess.py -i /media/storage/Experiments/DataSets/ISI_1MReq/ISI6 -o /media/storage/Experiments/DataSets/filtered/ISI_1MReq/ISI6
time python preprocess.py -i /media/storage/Experiments/DataSets/ISI_1MReq/ISI7 -o /media/storage/Experiments/DataSets/filtered/ISI_1MReq/ISI7
